
name: CI-CD-Pipe-To-Server

on:
  push:
    branches:
      - master

jobs:
   my_ci_pipeline:
      runs-on: ubuntu-latest
        steps:
	- name: Clone git repo
          uses: actions/checkout@v1
	- name: Create ZIP
	  run: zip -r PACKAGE.zip ./ -x *.git*

		
		
